# Generated by Django 5.0.6 on 2024-05-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assembly_code', models.CharField(max_length=200, unique=True)),
                ('assembly_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'assembly_line_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=200, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'product_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PackagedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('assembly_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline', to_field='assembly_code')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', to_field='product_code')),
            ],
            options={
                'db_table': 'pakaged_product_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DispatchedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('packaged_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packagedproduct')),
            ],
            options={
                'db_table': 'dispatched_product_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('assembly_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline', to_field='assembly_code')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', to_field='product_code')),
            ],
            options={
                'db_table': 'daily_inventory_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssemblyProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_qty', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('assembly_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline', to_field='assembly_code')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', to_field='product_code')),
            ],
            options={
                'db_table': 'assembly_product_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RejectProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('assembly_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'reject_product_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RepairProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('assembly_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'repair_product_table',
                'managed': True,
            },
        ),
    ]
