# Generated by Django 5.0.6 on 2024-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyproducts',
            name='assembly_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assemblyproducts',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
