# Generated by Django 5.0.6 on 2024-05-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dailyinventory_assembly_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyinventory',
            old_name='stock',
            new_name='initial_stock',
        ),
        migrations.AddField(
            model_name='dailyinventory',
            name='left_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
