# Generated by Django 5.0.6 on 2024-05-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_stock_dailyinventory_initial_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblyproducts',
            old_name='product_qty',
            new_name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='assemblyproducts',
            name='assembly_code',
        ),
        migrations.RemoveField(
            model_name='assemblyproducts',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='dailyinventory',
            name='assembly_code',
        ),
        migrations.RemoveField(
            model_name='dailyinventory',
            name='initial_stock',
        ),
        migrations.RemoveField(
            model_name='dailyinventory',
            name='left_stock',
        ),
        migrations.RemoveField(
            model_name='dailyinventory',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='packagedproduct',
            name='assembly_code',
        ),
        migrations.RemoveField(
            model_name='packagedproduct',
            name='product_code',
        ),
        migrations.AddField(
            model_name='assemblyproducts',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline', to_field='assembly_code'),
        ),
        migrations.AddField(
            model_name='assemblyproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', to_field='product_code'),
        ),
        migrations.AddField(
            model_name='dailyinventory',
            name='closing_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyinventory',
            name='inventory_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyinventory',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyinventory',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product', to_field='product_code'),
        ),
        migrations.AddField(
            model_name='packagedproduct',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline', to_field='assembly_code'),
        ),
        migrations.AddField(
            model_name='packagedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', to_field='product_code'),
        ),
    ]
