# Generated by Django 5.0.6 on 2024-05-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
