# Generated by Django 5.0.6 on 2024-05-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rejectproduct_date_repairproduct_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='repairproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='packagedproduct',
            name='closing_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagedproduct',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repairproduct',
            name='closing_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repairproduct',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
    ]
