# Generated by Django 5.0.6 on 2024-05-29 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_packagedproduct_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(blank=True, max_length=200, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=None)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'invoice_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoiceProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('assembly', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=None)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'invoice_product_table',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='dispatchedproduct',
            name='packaged_product',
        ),
        migrations.AddField(
            model_name='dispatchedproduct',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assemblyline', to_field='assembly_code'),
        ),
        migrations.AddField(
            model_name='dispatchedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', to_field='product_code'),
        ),
    ]
