# Generated by Django 5.0.6 on 2024-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_invoicedata_invoiceproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_user_name', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=None, max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('soft_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('soft_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'blacklist_token_table',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
